name: Create Release and Deploy to Staging

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Load .env.staging
        run: |
          set -o allexport
          source .env.staging
          set +o allexport

      - name: Install Dependencies
        run: npm ci

      - name: Build with Vercel
        run: npx vercel build --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: |
          npx vercel deploy \
            --prebuilt \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --prod \
            --yes