name: Create Release and Deploy to Preview

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  release_and_deploy:
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Pull Vercel environment variables
        run: |
          npx vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }}

      - name: Sync .env.preview to Vercel
        run: |
          # Push preview environment variables to Vercel
          npx vercel env add .env.preview --environment=preview --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build project
        run: |
          npx vercel build --environment=preview --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Preview
        run: |
          npx vercel deploy \
            --prebuilt \
            --environment=preview \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --yes \
            --force

      - name: Slack success notification
        if: success()
        uses: kranthisai-1/workflows/slack-alert@main
        with:
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          title: "✅ Preview Deployment Complete"
          message: "A new preview version was deployed."
          message_type: "success"