name: Preview Deployment

on:
  push:
    branches: [main]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Link Vercel project
        run: |
          npx vercel link --yes --token ${{ secrets.VERCEL_TOKEN }} \
            --project prj_BxoaUQaP1tgrZr5WmjZiwvHc2K91 \
            --scope team_hbtqJO0t3tEq8rpWJdcoYkDZ

      - name: Prepare Preview Environment
        run: |
          # 1. Backup existing .env.local
          [ -f .env.local ] && cp .env.local .env.local.bak || true
          
          # 2. Create temporary .env.local from .env.preview
          cp .env.preview .env.local
          
          # 3. Add environment marker
          echo "VERCEL_ENV=preview" >> .env.local

      - name: Build with Preview Variables
        run: |
          npx vercel build --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Preview
        run: |
          npx vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }} \
            --target=preview --yes --force

      - name: Cleanup Environment Files
        if: always()
        run: |
          # Remove temporary .env.local
          rm -f .env.local
          # Restore original if it existed
          [ -f .env.local.bak ] && mv .env.local.bak .env.local || true

      - name: Verify Deployment
        run: |
          echo "Preview deployment complete"
          echo "Environment variables used:"
          grep -v '^#' .env.preview