name: Tag-based Staging Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Create release version
        id: release
        uses: kranthisai-1/workflows/semantic-release@main

      - name: Slack Notification - Release Success
        if: ${{ steps.release.outputs.version != '' }}
        uses: kranthisai-1/workflows/slack-alert@main
        with:
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          title: "Release successful"
          message: "New version `v${{ steps.release.outputs.version }}` has been released."
          message_type: "success"

      - name: Slack Notification - Release Failed
        if: ${{ steps.release.outputs.version == '' }}
        uses: kranthisai-1/workflows/slack-alert@main
        with:
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          title: "Release failed"
          message: "Pushed to `main`, but release version could not be created."
          message_type: "danger"

  build:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Prepare Environment
        run: cp .env.staging .env.local

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Project Settings
        run: vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build Project with Vercel
        run: vercel build --token ${{ secrets.VERCEL_TOKEN }}

      - name: Archive Build Output
        run: tar -czf vercel-output.tgz .vercel

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vercel-build
          path: vercel-output.tgz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: vercel-build
          path: .

      - name: Extract Build Archive
        run: tar -xzf vercel-output.tgz

      - name: Deploy Prebuilt Project
        run: |
          vercel deploy --prebuilt --archive=tgz --token ${{ secrets.VERCEL_TOKEN }} \
            --target=preview --yes --force

      - name: Slack Notification - Deploy Success
        if: ${{ success() }}
        uses: kranthisai-1/workflows/slack-alert@main
        with:
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          title: "Staging Deployment Complete"
          message: "Latest build has been deployed to *staging*."
          message_type: "success"
