name: Preview Deployment

on:
  push:
    branches:
      -main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Create release version
        id: release
        uses: kranthisai-1/workflows/semantic-release@main

      - name: Link Vercel project
        run: |
          npx vercel link --yes --token ${{ secrets.VERCEL_TOKEN }} \
            --project prj_BxoaUQaP1tgrZr5WmjZiwvHc2K91 \
            --scope team_hbtqJO0t3tEq8rpWJdcoYkDZ

      - name: Prepare Preview Environment
        run: |
          [ -f .env.local ] && cp .env.local .env.local.bak || true
          cp .env.preview .env.local

      - name: Pull Project Settings
        run: npx vercel pull --yes --token ${{ secrets.VERCEL_TOKEN }} --environment=preview

      - name: Build with Preview Variables
        run: |
          npx vercel build --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Preview
        run: |
          npx vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }} \
            --target=preview --yes --force

      - name: Cleanup Environment Files
        if: always()
        run: |
          rm -f .env.local
          [ -f .env.local.bak ] && mv .env.local.bak .env.local || true

      - name: Send Slack success notification
        if: ${{ success() && steps.release.outputs.version != '' }}
        uses: kranthisai-1/workflows/slack-alert@main
        with:
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          title: "✅ Staging Deployment Complete"
          message: "Version `v${{ steps.release.outputs.version }}` was deployed to *staging*."
          message_type: "success"