name: Create Release and Deploy to Preview

on:
  push:
    branches:
      - main  # or use a different branch if preview builds are triggered elsewhere

permissions:
  id-token: write
  contents: read

jobs:
  release_and_deploy:
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Pull environment variables
        run: |
          npx vercel pull --yes --token ${{ secrets.VERCEL_TOKEN }}

      - name: Sync .env.preview
        run: |
          # Add/update preview environment variables
          npx vercel env add .env.preview --prebuilt --yes --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build and deploy
        run: |
          npx vercel deploy \
            --prebuilt \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --yes \
            --force \
            --env VERCEL_ENV=preview