name: Create Release and Deploy to Staging

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  release_and_deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # - name: Create release version
      #   id: release
      #   uses: kranthisai-1/workflows/semantic-release@main

      - name: Load .env.staging and deploy to Vercel (Staging)
        run: |
          # Load environment variables from .env.staging
          set -o allexport
          source .env.staging
          set +o allexport

          # Deploy to Vercel with the loaded env variables
          npx vercel deploy \
            --prebuilt \
            --cwd ./.next/standalone \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --prod \
            --yes \
            --name deploy-nextjs
          
      - name: Send Slack success notification
        if: ${{ success() && steps.release.outputs.version != '' }}
        uses: kranthisai-1/workflows/slack-alert@main
        with:
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          title: "✅ Staging Deployment Complete"
          message: "Version `v${{ steps.release.outputs.version }}` was deployed to *staging*."
          message_type: "success"
